### ISSUE TITLE
how to center items

### ISSUE THREAD

**Issue by milymat** [SunGard-Labs/angular-packery#19]
Hi,

it is not possible center the items in packery like this:
http://codepen.io/desandro/pen/xEzKo

How can I change this?

**Comment by joshuahiggins** [comment]
The example you've included shows the Packery object centered. This can be accomplished by applying appropriate CSS to the container element. For instance:

HTML:
``` html
<div class="container">
    <packery class="centerme">
        <packery-object>Obj 1</packery-object>
        <packery-object>Obj 2</packery-object>
        <packery-object>Obj 3</packery-object>
        <packery-object>Obj 4</packery-object>
    </packery>
</div>
```

CSS:
``` css
.container {
    width: 100%;
}
.centerme {
    margin: 0 auto;
}
```
