### ISSUE TITLE
Expose Packery object

### ISSUE THREAD

**Issue by filipesilva** [SunGard-Labs/angular-packery#33]
Hi, 

I'm using angular-packery in a project, and we have an element that changes size (as we post some data there). This causes a problem as packery is not relocating other elements to allow for that.

I see there's a [fit method in the Packery API](http://packery.metafizzy.co/methods.html#fit) but the only place I find in angular-packery to access the object directly is a broadcast on rootscope. 

Is there a better way to bind this object and use fit? Or is this maybe something on the roadmap, such as the support for stamp?

**Comment by joshuahiggins** [comment]
This is available in the current build. The Packery object is also added as a data object on the wrapper. You can access it utilizing

**Comment by joshuahiggins** [comment]
Sorry... On my phone and my thumb slipped. 

You can access it with angular.element's data("Packery").

**Comment by filipesilva** [comment]
Oh nice, now I have it. Also, thanks for the swift reply!
